hh

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -66,22 +66,29 @@ services:
       - db
 
     command: >
-      bash -lc "
-      set -e;
-
-      export MYSQL_PWD=${DB_ROOT_PASSWORD};
-
-      bench new-site mail.techvision.edu.et \
-        --admin-password admin \
-        --mariadb-root-password ${DB_ROOT_PASSWORD} \
-        --db-host db \
+      wait-for-it -t 120 db:3306;
+      wait-for-it -t 120 redis-cache:6379;
+      wait-for-it -t 120 redis-queue:6379;
+      export start=`date +%s`;
+      until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] &&
+        [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] &&
+        [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+      do
+        echo "Waiting for config...";
+        sleep 5;
+        if (( `date +%s`-start > 120 )); then
+          echo "Config not found";
+          exit 1
+        fi
+      done;
+      bench new-site \
+        --mariadb-user-host-login-scope='%' \
+        --admin-password=${ADMIN_PASSWORD} \
+        --db-root-username=root \
+        --db-root-password=${MYSQL_ROOT_PASSWORD} \
         --install-app erpnext \
         --install-app mail \
-        --force \
-        --no-input;
-
-      echo 'DONE';
-      "
+        --set-default ${SITE_NAME};
 
 
   db:
